clc;
clear;
daTrain = readtable('TrainsetTugas1ML.csv');
daTest = readtable('TestsetTugas1ML.csv');
prediksi = {};
pincome = unique(daTrain.income);
trainsetKaya = strcmp(daTrain.income,'>50K' );
trainsetMiskin = strcmp(daTrain.income,'<=50K' );
trainKaya = find(trainsetKaya);
trainMiskin = find(trainsetMiskin);
probKaya = length(trainKaya)/size(daTrain,1);
probMiskin = length(trainMiskin)/size(daTrain,1);

for i=1 : size(daTest,1)
    age1 = ( ...
        length( ...
        find(strcmp(daTrain.age,cell2mat(daTest.age(i))) ...
        &  strcmp(daTrain.income,cell2mat(pincome(1))))) ...
        / length(find(strcmp(daTrain.income,cell2mat(pincome(1))))) ...
        );
           
       workclass1 = ( ...
           length( ...
           find(strcmp(daTrain.workclass,cell2mat(daTest.workclass(i))) ...
           &  strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           / length(find(strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           );

       education1 = ( ...
           length( ...
           find(strcmp(daTrain.education,cell2mat(daTest.education(i))) ...
           &  strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           / length(find(strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           );

       marital_status1 = ( ...
           length( ...
           find(strcmp(daTrain.marital_status,cell2mat(daTest.marital_status(i))) ...
           &  strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           / length(find(strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           );

       occupation1 = ( ...
           length( ...
           find(strcmp(daTrain.occupation,cell2mat(daTest.occupation(i))) ...
           &  strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           / length(find(strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           );

       relationship1 = ( ...
           length( ...
           find(strcmp(daTrain.relationship,cell2mat(daTest.relationship(i))) ...
           &  strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           / length(find(strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           );

       hours_per_week1 = ( ...
           length( ...
           find(strcmp(daTrain.hours_per_week,cell2mat(daTest.hours_per_week(i))) ...
           &  strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           / length(find(strcmp(daTrain.income,cell2mat(pincome(1))))) ...
           );

        age2 = ( ...
           length( ...
           find(strcmp(daTrain.age,cell2mat(daTest.age(i))) ...
           &  strcmp(daTrain.income,cell2mat(pincome(2))))) ...
           / length(find(strcmp(daTrain.income,cell2mat(pincome(2))))) ...
           );
              
          workclass2 = ( ...
              length( ...
              find(strcmp(daTrain.workclass,cell2mat(daTest.workclass(i))) ...
              &  strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              / length(find(strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              );
   
          education2 = ( ...
              length( ...
              find(strcmp(daTrain.education,cell2mat(daTest.education(i))) ...
              &  strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              / length(find(strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              );
   
          marital_status2 = ( ...
              length( ...
              find(strcmp(daTrain.marital_status,cell2mat(daTest.marital_status(i))) ...
              &  strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              / length(find(strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              );
   
          occupation2 = ( ...
              length( ...
              find(strcmp(daTrain.occupation,cell2mat(daTest.occupation(i))) ...
              &  strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              / length(find(strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              );
   
          relationship2 = ( ...
              length( ...
              find(strcmp(daTrain.relationship,cell2mat(daTest.relationship(i))) ...
              &  strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              / length(find(strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              );
   
          hours_per_week2 = ( ...
              length( ...
              find(strcmp(daTrain.hours_per_week,cell2mat(daTest.hours_per_week(i))) ...
              &  strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              / length(find(strcmp(daTrain.income,cell2mat(pincome(2))))) ...
              );
           
       
       if(age1*workclass1*education1*marital_status1*occupation1*relationship1) > (age2*workclass2*education2*marital_status2*occupation2*relationship2)
            prediksi{i} = '>50K';
       
       else
            prediksi{i} = '<=50K';
       end
       
       writetable(cell2table(prediksi'),'TebakanTugas1ML.xlsx');
end

